--Task 3. Aggregate functions, Having, Order By, GroupBy and Joins: 
use TechShop;

--1. Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order.
select o.OrderID,c.First_Name,c.Last_Name,c.CID from Orders o
JOIN Customers c ON o.CID = c.CID;

--2. Write an SQL query to find the total revenue generated by each electronic gadget product. Include the product name and the total revenue.
Select p.PID, p.Product_Name, sum(p.Price* o.Quantity) as Totalrevenue from OrderDetails o 
JOIN Products p on o.PID= p.PID 
group by p.PID,p.Product_Name; 

--3. Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information.
select c.CID, c.First_Name, c.Last_Name, c.Email_Id, c.PhoneNo, c.Address  from Customers c 
JOIN Orders o ON c.CID = o.CID 
group by c.CID, c.First_Name, c.Last_Name, c.Email_Id, c.PhoneNo, c.Address;

--4. Write an SQL query to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered.
select p.PID ,p.Product_Name, sum(od.quantity) from products p 
JOIN orderdetails od ON p.PID = od.PID
group by p.PID, p.Product_Name;

--5. Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories.
select p.PID, p.Product_Name, i.InventoryID from Products p 
JOIN Inventory i ON p.PID = i.PID; 

--6. Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value.
select c.First_Name, c.Last_Name, avg(o.TotalAmount)as avgordervalue from Customers c 
JOIN Orders o ON c.CID = o.CID group by c.CID, c.First_Name, c.Last_Name; 

--7. Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue.
select o.OrderID, c.First_Name, c.Last_Name, c.CID, c.Email_Id, c.Address, o.TotalAmount from Customers c 
JOIN Orders o ON c.CID = o.CID 
where o.TotalAmount = (select max(TotalAmount) from Orders);

--8. Write an SQL query to list electronic gadgets and the number of times each product has been ordered.
select top 1 p.PID, p.Product_Name, count(od.OrderID) as Timesoforder from Products p 
JOIN OrderDetails od ON p.PID = od.PID 
JOIN Orders o ON od.OrderID=o.OrderID
group by p.PID,p.Product_Name
order by Timesoforder desc;

--9. Write an SQL query to find customers who have purchased a specific electronic gadget product. Allow users to input the product name as a parameter.
select c.CID, c.First_Name, c.Last_Name, c.Email_Id, c.PhoneNo, c.Address from Customers c 
JOIN Orders o ON o.CID = c.CID 
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.PID = p.PID  
where p.Product_Name = 'Laptop';

--10. Write an SQL query to calculate the total revenue generated by all orders placed within a specific time period. Allow users to input the start and end dates as parameters.
select sum(TotalAmount) from Orders 
where OrderDate BETWEEN '2025-01-01'  AND '2025-01-31';
