--Task 4. Subquery and its type: 
use TechShop;

--1. Write an SQL query to find out which customers have not placed any orders.
select c.CID, c.First_Name, c.Last_Name from Customers c 
LEFT JOIN Orders o ON c.CID = o.CID 
where o.OrderID is null;

--2. Write an SQL query to find the total number of products available for sale.  
select count(*) from Products;

--3. Write an SQL query to calculate the total revenue generated by TechShop.  
select sum(TotalAmount) from Orders;
select * from Orders;

--4. Write an SQL query to calculate the average quantity ordered for products in a specific category. Allow users to input the category name as a parameter.
select avg(o.Quantity) from OrderDetails o
JOIN Products p ON o.PID=p.PID
where p.Product_Name ='Laptop';

--5. Write an SQL query to calculate the total revenue generated by a specific customer. Allow users to input the customer ID as a parameter.
select sum(o.TotalAmount) from Orders o 
JOIN Customers c ON o.CID = c.CID 
where o.CID = '109';

--6. Write an SQL query to find the customers who have placed the most orders. List their names and the number of orders they've placed.
select c.First_Name, c.Last_Name, count(o.OrderID) from Customers c 
LEFT JOIN Orders o ON c.CID = o.CID 
group by First_Name, Last_Name ;

select c.First_Name, c.Last_Name, count(o.OrderID) as NoofOrders from Customers c 
join Orders o on c.CID = o.CID group by First_Name, Last_Name 
order by NoofOrders desc;

--7. Write an SQL query to find the most popular product category, which is the one with the highest total quantity ordered across all orders.
select p.PID, p.Product_Name, p.Price from Products p 
JOIN OrderDetails od ON p.PID = od.PID 
where od.Quantity = (select max(Quantity) from OrderDetails)
order by p.PID DESC;

--8. Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets. List their name and total spending.
select top 1 c.CID, c.First_Name, c.Last_Name, sum(o.TotalAmount) as Totalrevenue from Customers c 
JOIN Orders o ON c.CID = o.CID 
group by c.CID, c.First_Name, c.Last_Name
order by Totalrevenue desc;


--9. Write an SQL query to calculate the average order value (total revenue divided by the number of orders) for all customers.
select avg(TotalAmount)  from Orders; 

--10. Write an SQL query to find the total number of orders placed by each customer and list their names along with the order count
select c.CID,c.First_Name, c.Last_Name, count(o.OrderID) as countoforders from Customers c 
JOIN Orders o ON c.CID = o.CID 
group by c.CID,c.First_Name, c.Last_Name 
order by countoforders desc; 